# Generated by Django 3.1.4 on 2020-12-25 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_clone_helper', '0003_auto_20201221_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='BassGuitar',
            fields=[
                ('instrument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_clone_helper.instrument')),
                ('type', models.CharField(choices=[('AC', 'Acoustic'), ('EL', 'Electric')], default='EL', max_length=2)),
            ],
            bases=('django_clone_helper.instrument',),
        ),
    ]
