# Generated by Django 3.1.4 on 2020-12-26 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_clone_helper', '0004_bassguitar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_clone_helper.song')),
            ],
        ),
    ]
